dubbo:
  application:
    name: healthy-consumer-rest-api
  registry:
    protocol: zookeeper
    address: 39.106.60.71:2181
  protocol:
    name: dubbo
    port: 20882
  version: 1.0.0
  scan:
    base-packages: com.etycx.rest

server:
  ssl:
    key-store: classpath:xcx.rongyijiankang.com.pfx
    key-store-password: zm617ipao91wrl7
    key-store-type: PKCS12
