dubbo:
  application:
    name: healthy-provider-wechat
  registry:
    protocol: zookeeper
    address: 39.106.60.71:2181
  protocol:
    name: dubbo
    port: 20881
  version: 1.0.0
  scan:
    base-packages: com.etycx.wechat